#ifndef __CONFIG_H
#define __CONFIG_H
#define LK 1
#define MTK_NEW_COMBO_EMMC_SUPPORT
#define MTK_DLPT_SUPPORT
#define WITH_DEBUG_UART 1
#define MTK_GPT_SCHEME_SUPPORT
#define BUILD_LK
#define SKIP_MTK_PARTITION_HEADER_CHECK
#define MTK_GPT_SCHEME_SUPPORT
#define MEMBASE 0X41E00000
#define SCRATCH_ADDR 0X45000000
#define DEVICE_TREE_SUPPORT
#define MTK_FASTBOOT_SUPPORT
#define LK_PROFILING
#define SELINUX_STATUS 3
#define PERIPH_BLK_BLSP 1
#define WITH_CPU_EARLY_INIT 0
#define WITH_CPU_WARM_BOOT 0
#define MMC_SLOT 1
#define MTK_SECURITY_SW_SUPPORT
#define MTK_SEC_FASTBOOT_UNLOCK_SUPPORT
#define MTK_OFF_MODE_CHARGE_SUPPORT
#define CMCC_LTE_FHD
#define MTK_KERNEL_POWER_OFF_CHARGING
#define ARM_CPU_CORTEX_A7 1
#define ARM_WITH_CP15 1
#define ARM_WITH_MMU 1
#define ARM_ISA_ARMV7 1
#define ARM_WITH_VFP 1
#define ARM_WITH_NEON 1
#define ARM_WITH_THUMB 1
#define ARM_WITH_THUMB2 1
#define ARM_WITH_CACHE 1
#define ARM_WITH_L2 1
#define R63417_FHD_DSI_CMD_TRULY_NT50358
#define MTK_LCM_PHYSICAL_ROTATION "0"
#define LCM_WIDTH ""
#define LCM_HEIGHT ""
#define MACH_TYPE 6753
#define BOARD MEIZU6753_65C_L1
#define PROJECT_MEIZU6753_65C_L1 1
#define TARGET_MEIZU6753_65C_L1 1
#define PLATFORM_MT6735 1
#define ARCH_ARM 1
#define MACH_TYPE_MT6753 1
#define WITH_APP_MT_BOOT 1
#define WITH_DEV_KEYS 1
#define WITH_DEV_LCM 1
#define WITH_DEV_VIDEO 1
#define WITH_LIB_DEBUG 1
#define WITH_LIB_HEAP 1
#define WITH_LIB_LIBC 1
#define WITH_LIB_LIBFDT 1
#define WITH_LIB_LIBSHOWLOGO 1
#define WITH_LIB_OPENSSL 1
#define WITH_LIB_PTABLE 1
#define WITH_LIB_ZLIB 1
#define MTK_EMMC_SUPPORT
#define MTK_SECURITY_SW_SUPPORT
#define MTK_VERIFIED_BOOT_SUPPORT
#define DEBUG 0
#endif
